//Exercise 5: Write a C# program to allow a user to guess a number( from
//1 to 6) that will be randomly generated by computer.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace C_Practice
{
    public class 
    internal class GuessANumber
    {
    }
}
